### 기본
GET http://localhost:8000/ HTTP/1.1

### 전체 목록
GET http://localhost:8000/posts/ HTTP/1.1

### 특정 아이디 조회
GET http://localhost:8000/posts/2 HTTP/1.1

### delete
DELETE http://localhost:8000/posts/4 HTTP/1.1

### 등록
POST http://localhost:8000/posts/ HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
    "title": "테스트 제목1",
    "content": "테스트 내용1",
    "author": "작성자 이름1"
}
